// `.env.ts` is generated by the `npm run env` command
// import env from '@env/.env';
import { env } from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,

  serverUrl: 'https://prodapi.sportgrit.com/api/v2/',
  imageUrl: 'https://prodapi.sportgrit.com/',
  resetpasswordurl: 'https://prodapi.sportgrit.com/manage/forgotPassword',

  Platform_Admin: 'PLA',
  Family_Friends_Fans: 'FFF',
  Club_Admin: 'CAD',
  Super_Admin: 'SAD',
  Coach: 'COA',
  Parent: 'PAR',
  Recruiter: 'REC',
  Athlete: 'ATH',
  match: 'Match',
  tryouts: 'Tryouts',
  defaultLanguage: 'en-US',

  firebase: {
    apiKey: 'AIzaSyAl-bx0-N5foKCKJ6TV8wuYVUsbhQCRLxQ',
    // authDomain: 'sportsgrit-77a4b.firebaseapp.com',
    // databaseURL: 'https://sportsgrit-77a4b.firebaseio.com',
    projectId: 'sportsgrit-77a4b',
    storageBucket: 'sportsgrit-77a4b.appspot.com',
    messagingSenderId: '42507948141'
  },
  supportedLanguages: ['en-US', 'fr-FR']
};
